// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// Android Firebase Options
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmU0DD8xskfIuCwk4cWrWNlBE_7WKgWPY',
    appId: '1:795881679205:android:5a9358b6af50f07e0c198c',
    messagingSenderId: '795881679205',
    projectId: 'leafapp-93b4b',
    storageBucket: 'leafapp-93b4b.appspot.com',
  );

// iOS Firebase Options
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmU0DD8xskfIuCwk4cWrWNlBE_7WKgWPY',
    appId: '1:795881679205:ios:5a9358b6af50f07e0c198c',
    messagingSenderId: '795881679205',
    projectId: 'leafapp-93b4b',
    storageBucket: 'leafapp-93b4b.appspot.com',
    iosBundleId: 'leaf.app',
  );


}
